[ 2 of 12] Compiling Model            ( Model.hs, Model.o )
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package array-0.4.0.0 ... linking ... done.
Loading package bytestring-0.9.2.1 ... linking ... done.
Loading package deepseq-1.3.0.0 ... linking ... done.
Loading package containers-0.4.2.1 ... linking ... done.
Loading package text-0.11.2.3 ... linking ... done.
Loading package attoparsec-0.10.4.0 ... linking ... done.
Loading package blaze-builder-0.3.1.0 ... linking ... done.
Loading package dlist-0.5 ... linking ... done.
Loading package hashable-1.2.0.5 ... linking ... done.
Loading package transformers-0.3.0.0 ... linking ... done.
Loading package mtl-2.1.2 ... linking ... done.
Loading package old-locale-1.0.0.4 ... linking ... done.
Loading package syb-0.4.0 ... linking ... done.
Loading package pretty-1.1.1.0 ... linking ... done.
Loading package template-haskell ... linking ... done.
Loading package time-1.4 ... linking ... done.
Loading package unordered-containers-0.2.3.0 ... linking ... done.
Loading package primitive-0.5.0.1 ... linking ... done.
Loading package vector-0.10.0.1 ... linking ... done.
Loading package aeson-0.6.1.0 ... linking ... done.
Loading package base-unicode-symbols-0.2.2.4 ... linking ... done.
Loading package transformers-base-0.4.1 ... linking ... done.
Loading package monad-control-0.3.1.4 ... linking ... done.
Loading package base64-bytestring-1.0.0.1 ... linking ... done.
Loading package blaze-markup-0.5.1.4 ... linking ... done.
Loading package blaze-html-0.6.0.0 ... linking ... done.
Loading package lifted-base-0.2.0.2 ... linking ... done.
Loading package resourcet-0.4.5 ... linking ... done.
Loading package nats-0.1 ... linking ... done.
Loading package semigroups-0.9 ... linking ... done.
Loading package void-0.5.11 ... linking ... done.
Loading package conduit-1.0.2 ... linking ... done.
Loading package date-cache-0.3.0 ... linking ... done.
Loading package filepath-1.3.0.0 ... linking ... done.
Loading package old-time-1.1.0.0 ... linking ... done.
Loading package unix-2.5.1.1 ... linking ... done.
Loading package directory-1.1.0.2 ... linking ... done.
Loading package unix-time-0.1.6 ... linking ... done.
Loading package fast-logger-0.3.1 ... linking ... done.
Loading package monad-logger-0.3.0.1 ... linking ... done.
Loading package path-pieces-0.1.2 ... linking ... done.
Loading package stm-2.4.2 ... linking ... done.
Loading package resource-pool-0.2.1.1 ... linking ... done.
Loading package pool-conduit-0.1.1 ... linking ... done.
Loading package silently-1.2.4.1 ... linking ... done.
Loading package persistent-1.1.5.1 ... linking ... done.
Loading package persistent-template-1.1.2.4 ... linking ... done.
