Default: &defaults
  database: helloworld.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: helloworld_test.sqlite3
  <<: *defaults

Staging:
  database: helloworld_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: helloworld_production.sqlite3
  poolsize: 100
  <<: *defaults
